== Getting Started

The focus of this section is to help you find and purchase a basic set of items and install the software you'll need to get started creating your own alternative controllers. After testing many different hardware platforms, including official Arduino boards or Raspberry Pi devices, we have landed on the Teensy line of microcontroller development board.

More specifically, this guide is primarily focused on the https://www.pjrc.com/teensy/teensyLC.html[Teensy LC] and https://www.pjrc.com/store/teensy32.html[Teensy 3.1 / 3.2] boards. Examples will assume you are using a Teensy LC, but whenever possible it will work on Teensy 3.x boards as well and differences will be called out when important.

There are many ways to peel a potato, so whether it be the best parts to buy, the best way to connect those parts, or the best way to make the code as simple as possible, I think it is important to remember that just getting it all to _work_ is the the victory we are trying to achieve here.

You may find a better way to do something, and that's great! I recommend doing it my way first and once you _have_ gotten something to work it'll be easier to test your ideas to see if they work _even better_. Don't doubt yourself just because I recommended something different!